.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "MBCHECK" "1" "March 2013" "" ""
.
.SH "NAME"
\fBmbcheck\fR \-\- Check an mbtiles for missing metadata and tiles
.
.SH "SYNOPSIS"
\fBmbcheck\fR <file>
.
.SH "DESCRIPTION"
The mbcheck(1) command checks an mbtiles archive for missing
metadata and tiles\.
.
.SH "OPTIONS"
\fB\-\-help\fR display this help and exit
.
.SH "EXAMPLES"
mbcheck world\.mbtiles
.
.SH "AUTHOR"
Written by MapBox\.
.
.SH "REPORTING BUGS"
Please report bugs on the GitHub issue tracker:
<\fBhttps://github\.com/mapbox/node\-mbtiles/issues\fR>
.
.SH "SEE ALSO"
mbcompact(1), mbpipe(1), mbrekey(1)
