.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "MBCOMPACT" "1" "March 2013" "" ""
.
.SH "NAME"
\fBmbcompact\fR \-\- Eliminate duplicate images to reduce mbtiles file size
.
.SH "SYNOPSIS"
\fBmbcompact\fR <file>
.
.SH "DESCRIPTION"
The mbcompact(1) command eliminates duplicate images to reduce
the size of an mbtiles archive\.
.
.SH "OPTIONS"
\fB\-\-help\fR display this help and exit
.
.SH "EXAMPLES"
mbcompact world\.mbtiles
.
.SH "AUTHOR"
Written by MapBox\.
.
.SH "REPORTING BUGS"
Please report bugs on the GitHub issue tracker:
<\fBhttps://github\.com/mapbox/node\-mbtiles/issues\fR>
.
.SH "SEE ALSO"
mbcheck(1), mbpipe(1), mbrekey(1)
